---
title: "Comparing ML and PML Estimates"
runtime: shiny
output: html_document
---

```{r global_options, include=FALSE}
wd <- normalizePath("../")
wd
knitr::opts_knit$set(fig.path='fig/',
               echo=FALSE, warning=FALSE, message=FALSE,
               root.dir=wd)
```


```{r, echo = FALSE}
# load packages
library(ggplot2)
library(dplyr)
library(readr)
library(tidyr)

# plot parameter
theme <- theme_gray()

# read data
sims <- read_csv("R/simulations/sims.csv")

# collapse all stats into single column
sims_tall <- gather(sims, stat, value, ev:mse)

# set inputs
inputPanel(
  radioButtons("stat", label = "Statistic:",
              choices = c("Expected Value" = "ev", 
                          "Bias" = "bias",
                          "Percent Bias" = "percent_bias", 
                          "Variance" = "var",
                          "Mean-Squared Error" = "mse"), 
              selected = "percent_bias"),
  radioButtons("k", label = "Number of Variables:",
              choices = c(3, 6, 9)),
  radioButtons("b0", label = "Intercept:",
              choices = c(-1, -0.5, 0))
  )

# render plot
renderPlot(
  {
    stat_subset_data <- subset(sims_tall, stat == input$stat)
    ymin <- with(stat_subset_data, min(value))
    ymax <- with(stat_subset_data, max(value))
    subset_data <- subset(sims_tall, k == input$k & 
                            b0 == input$b0 & 
                            stat == input$stat)
    print(glimpse(subset_data))
    ggplot(subset_data, aes(x = n, y = value, color = method)) +
      geom_point() +
      geom_line() +
      scale_y_continuous(limits = c(ymin, ymax)) +
      labs(x = "Sample Size") +
      labs(color = "Method") +
      labs(y = "Statistic")
    }
  )
```
